platform :ios, '6.0'
pod 'SDLayoutView', :path => 'SDLayoutView'
pod 'AFNetworking', '~> 1.3.0'
pod 'SDWebImage', '>= 3.0'
pod 'MarqueeLabel', :podspec => 'Scripts/Podspecs/MarqueeLabel.podspec'
pod 'TestFlightSDK'
